### ISSUE TITLE
Installing Compressions Uninstalls any and all resource packs

### ISSUE THREAD

**Issue by MokahTGS** [Sediments/Compressions#5]
So not a huge deal but when you add Compressions (or patch it) it uninstalled any texture pack you have previously.

**Comment by Sediments** [comment]
You mean other people's resource packs? Or just the "Compressions.zip"? Because it's suppose to remove the "Compressions.zip". As I change how the textures look between versions. But I also don't generate the textures if they are already in the resource pack. So my current workaround is to "refresh" the resource pack when I publish a new version.

**Comment by Sediments** [comment]
Oh god, your right. I made a slight adjustment recently and I'm accidentally unregistering all the resource packs. Will be fixed shortly.
