### ISSUE TITLE
problems with texture generation 

### ISSUE THREAD

**Issue by Varg95** [Sediments/Compressions#6]
https://pastebin.com/mzp0mf9k i got this crash report when the mod is installed.

**Comment by Sediments** [comment]
Do you change the size of the window after you enter the game?

I capture the screen after forge is done loading and display it when I'm generating the textures (Otherwise there's an ugly black screen). It seems I did not consider the possibility that the minecraft window size might change in between these two things (Since they happen right after each other). Will fix shortly.

**Comment by Varg95** [comment]
it now load but the textures are black and purple

**Comment by Sediments** [comment]
That's weird, I didn't touch anything that generates the textures, just the display of that one captured image.

Try deleting the resource pack (the 'Compressions.zip' file) and let me know if that worked.

**Comment by Varg95** [comment]
it worked but when i changed the config it didn't anymore. And it seems i can't change the depth or amount of compressions

**Comment by Sediments** [comment]
Could you show me how your config file looks like?

**Comment by Varg95** [comment]
https://pastebin.com/YuQiQxeh here is a pastebin

**Comment by Sediments** [comment]
You're not setting the 'Width' and 'Height' properties?

**Comment by Varg95** [comment]
oh okay my bad sorry.

**Comment by Sediments** [comment]
No problem, I'm glad to have helped you solve your problem.
